"""Render a populated Matched_Listing form per evaluated listing.

Two outputs:
  render_form()       -> markdown (for diff-ability and CLI viewing)
  render_form_html()  -> HTML with clickable citations that open the source
                          PDF at the cited page. Open in any modern browser
                          (Edge, Chrome, Firefox) — clicking a citation uses
                          the standard PDF #page=N URL fragment.

Both layouts mirror the UMass Chan DES form:
  - Header (DIAGNOSIS, CASE #, listing code + title)
  - Each criterion with met/not/insufficient checkbox
  - Tri-state verdict (Meets / Equals / Does not meet/equal)
  - Objective Medical Evidence narrative composed from per-leaf citations
  - Citations index at the end
"""
from html import escape
from pathlib import Path
from urllib.parse import quote

from .chunks import Chunk, Listing
from .consolidate import NodeVerdict, form_verdict
from .evaluate import LeafResult


def render_form(
    listing: Listing,
    root_verdict: NodeVerdict,
    leaf_results: dict[str, LeafResult],
    case_id: str,
    chunks_by_id: dict[str, Chunk],
) -> str:
    lines = []
    lines.append("UNIVERSITY OF MASSACHUSETTS CHAN MEDICAL SCHOOL")
    lines.append("DISABILITY EVALUATION SERVICES — SSI LISTINGS — ADULT")
    lines.append("")
    lines.append(f"**DIAGNOSIS:** {listing.title}")
    lines.append(f"**CASE #:** {case_id}")
    lines.append("")
    lines.append(f"## {listing.code} — {listing.title}")
    lines.append(f"*Body system: {listing.body_system}*")
    lines.append("")
    lines.append("### Criteria")
    lines.append("")

    # Render every leaf with its verdict.
    citation_pool: list[tuple[str, Chunk, str]] = []  # (citation_marker, chunk, quote)
    citation_seen: dict[str, str] = {}  # chunk_id -> marker

    def cite(chunk_id: str, chunk: Chunk, quote: str) -> str:
        if chunk_id in citation_seen:
            return citation_seen[chunk_id]
        marker = f"[{len(citation_pool) + 1}]"
        citation_seen[chunk_id] = marker
        citation_pool.append((marker, chunk, quote))
        return marker

    def render_node(node: NodeVerdict, depth: int = 0):
        indent = "  " * depth
        if node.logic is None:
            # leaf
            box = _checkbox(node.verdict)
            lines.append(f"{indent}- {box} **{node.path}** — {node.criterion or ''}")
            lr = leaf_results.get(node.path)
            if lr and lr.rationale:
                lines.append(f"{indent}  *Rationale:* {lr.rationale}")
            if lr and lr.evidence:
                for ev in lr.evidence:
                    chunk = chunks_by_id.get(ev.chunk_id)
                    if not chunk:
                        continue
                    marker = cite(ev.chunk_id, chunk, ev.quote)
                    lines.append(
                        f"{indent}  - {marker} *{_chunk_label(chunk)}:* "
                        f"\"{ev.quote}\""
                    )
        else:
            # internal
            label = f"{node.path} ({node.logic})"
            if node.criterion:
                label += f" — {node.criterion}"
            box = _checkbox(node.verdict)
            lines.append(f"{indent}- {box} **{label}**")
            for child in node.children:
                render_node(child, depth + 1)

    render_node(root_verdict)
    lines.append("")

    # Top-level verdict.
    lines.append("### CHECK CRITERIA MET")
    lines.append("")
    verdict_label = form_verdict(root_verdict)
    lines.append(f"**Verdict:** **{verdict_label}**")
    lines.append("")
    lines.append(f"- {'☒' if verdict_label == 'Meets' else '☐'} Meets")
    lines.append("- ☐ Equals  *(equivalence reasoning not implemented in stub)*")
    lines.append(
        f"- {'☒' if verdict_label.startswith('Does not') else '☐'} Does not meet/equal"
    )
    if verdict_label.startswith("Insufficient"):
        lines.append(f"- ☒ Insufficient evidence — reviewer must verify against chart")
    lines.append("")
    lines.append("Disability Reviewer #: __________   Physician Advisor #: __________")
    lines.append("")

    # Objective medical evidence narrative.
    lines.append("### OBJECTIVE MEDICAL EVIDENCE AND OTHER ADDITIONAL INFORMATION")
    lines.append("")
    narrative = _compose_narrative(root_verdict, leaf_results, chunks_by_id, citation_seen, citation_pool, cite)
    lines.append(narrative)
    lines.append("")

    # Citations index.
    if citation_pool:
        lines.append("### Citations")
        lines.append("")
        for marker, chunk, _quote in citation_pool:
            lines.append(
                f"- {marker} `{chunk.chunk_id}` — "
                f"{_chunk_label(chunk)}"
            )
        lines.append("")

    lines.append("---")
    lines.append("*Auto-generated by stub pipeline. Reviewer must verify all citations against source PDF before signing.*")

    return "\n".join(lines)


def _checkbox(verdict: str) -> str:
    return {
        "met": "☒",
        "not_met": "☐",
        "insufficient": "?",
    }.get(verdict, "?")


def _chunk_label(chunk: Chunk) -> str:
    """Render a chunk's metadata as a human-readable citation tag."""
    bits = []
    if chunk.doc_title:
        bits.append(chunk.doc_title.split("—")[-1].strip() if "—" in chunk.doc_title else chunk.doc_title)
    elif chunk.doc_type:
        bits.append(chunk.doc_type.replace("_", " "))
    if chunk.section:
        bits.append(chunk.section)
    if chunk.encounter_date:
        bits.append(chunk.encounter_date)
    bits.append(f"p.{chunk.page_start}")
    return ", ".join(bits)


def _compose_narrative(
    root: NodeVerdict,
    leaf_results: dict,
    chunks_by_id: dict,
    citation_seen: dict,
    citation_pool: list,
    cite,
) -> str:
    """Compose a reviewer-facing prose summary from per-leaf evidence."""
    paragraphs = []

    def walk(node: NodeVerdict):
        if node.logic is None:
            lr = leaf_results.get(node.path)
            if not lr:
                return
            if node.verdict == "met" and lr.evidence:
                lines = [f"**{node.path} ({node.verdict}):** {lr.rationale}"]
                for ev in lr.evidence:
                    chunk = chunks_by_id.get(ev.chunk_id)
                    if not chunk:
                        continue
                    marker = cite(ev.chunk_id, chunk, ev.quote)
                    lines.append(
                        f"  > {marker} *{_chunk_label(chunk)}*:  \n"
                        f"  > \"{ev.quote}\""
                    )
                paragraphs.append("\n".join(lines))
            elif node.verdict == "not_met":
                paragraphs.append(
                    f"**{node.path}:** Not met. {lr.rationale}"
                )
            elif node.verdict == "insufficient":
                paragraphs.append(
                    f"**{node.path}:** Insufficient evidence in record. {lr.rationale}"
                )
        else:
            for c in node.children:
                walk(c)

    walk(root)
    if not paragraphs:
        return "*No per-criterion evidence available.*"
    return "\n\n".join(paragraphs)


def write_form(out_path: Path, content: str):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")


# =============================================================================
# HTML renderer with clickable page-level citations
# =============================================================================

def _pdf_page_link(source_pdf_path: Path | None, page: int) -> str | None:
    """Return a *relative* URL (just the PDF's filename) with #page=N fragment
    that all major PDF viewers honor (Adobe Reader, Edge/Chrome built-in viewer,
    Firefox PDF.js). Returns None if no source PDF path was provided.

    Convention: the source PDF is expected to live in the same directory as
    the HTML that references it (see run.py: annotated_pdf_path is written
    into out_dir alongside the *.html outputs). This keeps each case bundle
    self-contained — copy/zip output/<case_id>/ and every citation still works.
    """
    if not source_pdf_path:
        return None
    # quote() handles URL-encoding of spaces and other special chars in the
    # filename. We deliberately do NOT call .resolve().as_uri() — that would
    # produce an absolute file:// URL that breaks when the bundle is moved.
    return f"{quote(source_pdf_path.name)}#page={page}"


def render_form_html(
    listing: Listing,
    root_verdict: NodeVerdict,
    leaf_results: dict[str, LeafResult],
    case_id: str,
    chunks_by_id: dict[str, Chunk],
    source_pdf_path: Path | None = None,
) -> str:
    """Render an HTML form. Citation markers become clickable links that open
    the source PDF at the cited page. If source_pdf_path is None, citations
    render as plain text (with page numbers but no link).
    """
    verdict_label = form_verdict(root_verdict)

    # Track citations as we encounter them so we can render an index + reuse markers.
    citation_pool: list[tuple[str, Chunk, str]] = []
    citation_seen: dict[str, str] = {}

    def cite(chunk: Chunk, quote: str) -> str:
        if chunk.chunk_id in citation_seen:
            return citation_seen[chunk.chunk_id]
        marker = f"[{len(citation_pool) + 1}]"
        citation_seen[chunk.chunk_id] = marker
        citation_pool.append((marker, chunk, quote))
        return marker

    def cite_link(chunk: Chunk, quote: str) -> str:
        marker = cite(chunk, quote)
        href = _pdf_page_link(source_pdf_path, chunk.page_start)
        if href:
            return (
                f'<a class="cite" href="{escape(href)}" '
                f'title="Open packet PDF at p.{chunk.page_start}" '
                f'target="_blank" rel="noopener">{marker}</a>'
            )
        return f'<span class="cite">{marker}</span>'

    def render_node_html(node: NodeVerdict, depth: int = 0) -> str:
        indent_px = depth * 18
        if node.logic is None:
            box = _checkbox_html(node.verdict)
            lr = leaf_results.get(node.path)
            crit = escape(node.criterion or "")
            html = (
                f'<div class="leaf v-{node.verdict}" style="margin-left:{indent_px}px">'
                f'<div class="leaf-header">{box} <span class="leaf-path">{escape(node.path)}</span> '
                f'<span class="leaf-crit">— {crit}</span></div>'
            )
            if lr and lr.rationale:
                html += f'<div class="rationale"><em>Rationale:</em> {escape(lr.rationale)}</div>'
            if lr and lr.evidence:
                html += '<ul class="evidence">'
                for ev in lr.evidence:
                    chunk = chunks_by_id.get(ev.chunk_id)
                    if not chunk:
                        continue
                    marker_html = cite_link(chunk, ev.quote)
                    label = escape(_chunk_label(chunk))
                    quote_html = escape(ev.quote)
                    html += (
                        f'<li>{marker_html} '
                        f'<span class="cite-label">{label}:</span> '
                        f'<span class="quote">"{quote_html}"</span></li>'
                    )
                html += '</ul>'
            html += '</div>'
            return html
        else:
            box = _checkbox_html(node.verdict)
            label = f"{escape(node.path)} ({escape(node.logic)})"
            if node.criterion:
                label += f" — {escape(node.criterion)}"
            inner = "\n".join(render_node_html(c, depth + 1) for c in node.children)
            return (
                f'<div class="internal v-{node.verdict}" style="margin-left:{indent_px}px">'
                f'<div class="internal-header">{box} <strong>{label}</strong></div>'
                f'{inner}</div>'
            )

    body_criteria = render_node_html(root_verdict)

    # Build the narrative
    narrative_parts: list[str] = []

    def walk_narrative(node: NodeVerdict):
        if node.logic is None:
            lr = leaf_results.get(node.path)
            if not lr:
                return
            head = f'<h4 class="v-{node.verdict}">{escape(node.path)} ({node.verdict})</h4>'
            body = f'<p>{escape(lr.rationale)}</p>'
            quotes_html = ""
            if node.verdict == "met" and lr.evidence:
                quotes_html = '<ul class="evidence">'
                for ev in lr.evidence:
                    chunk = chunks_by_id.get(ev.chunk_id)
                    if not chunk:
                        continue
                    marker_html = cite_link(chunk, ev.quote)
                    label = escape(_chunk_label(chunk))
                    quote_html = escape(ev.quote)
                    quotes_html += (
                        f'<li>{marker_html} <span class="cite-label">{label}:</span> '
                        f'<blockquote class="quote">"{quote_html}"</blockquote></li>'
                    )
                quotes_html += '</ul>'
            narrative_parts.append(head + body + quotes_html)
        else:
            for c in node.children:
                walk_narrative(c)

    walk_narrative(root_verdict)
    narrative_html = "\n".join(narrative_parts) or "<p><em>No per-criterion evidence available.</em></p>"

    # Citations index
    citations_html = ""
    if citation_pool:
        rows = []
        for marker, chunk, _quote in citation_pool:
            href = _pdf_page_link(source_pdf_path, chunk.page_start)
            link = (
                f'<a href="{escape(href)}" target="_blank" rel="noopener">{marker}</a>'
                if href else marker
            )
            rows.append(
                f'<li>{link} <code>{escape(chunk.chunk_id)}</code> — '
                f'{escape(_chunk_label(chunk))}</li>'
            )
        citations_html = "<h3>Citations</h3><ol class=\"citations\">" + "".join(rows) + "</ol>"

    # Top-of-page link to the whole packet. Relative URL (just the filename)
    # so the bundle stays portable — see _pdf_page_link for the rationale.
    open_packet = ""
    if source_pdf_path:
        pkt_uri = quote(source_pdf_path.name)
        open_packet = (
            f'<p class="open-packet">'
            f'<a href="{escape(pkt_uri)}" target="_blank" rel="noopener">'
            f'Open source PDF: {escape(source_pdf_path.name)}</a></p>'
        )

    return _HTML_TEMPLATE.format(
        title=escape(f"{listing.code} — {listing.title}"),
        case_id=escape(case_id),
        listing_code=escape(listing.code),
        listing_title=escape(listing.title),
        body_system=escape(listing.body_system),
        verdict_label=escape(verdict_label),
        verdict_class={
            "Meets": "v-met",
            "Does not meet/equal": "v-not_met",
        }.get(verdict_label, "v-insufficient"),
        open_packet=open_packet,
        criteria_html=body_criteria,
        narrative_html=narrative_html,
        citations_html=citations_html,
    )


def _checkbox_html(verdict: str) -> str:
    return {
        "met": '<span class="box met">☒</span>',
        "not_met": '<span class="box not_met">☐</span>',
        "insufficient": '<span class="box insufficient">?</span>',
    }.get(verdict, '<span class="box">?</span>')


# =============================================================================
# Case-level summary HTML — one document aggregating all listings
# =============================================================================
#
# Output: a single 0_CASE_SUMMARY.html per case containing:
#   1. Headline summary (overall verdict, groundedness, candidate count)
#   2. 3-column table: Impairment Alleged | Medical Evidence Found | SSI Listing Met
#      (one row per allegation; cell content links to the detailed listing section)
#   3. Concatenated per-listing detail sections, prefixed with anchor IDs so
#      table links jump to the right form
#
# Designed to be the reviewer's single-page entry point — they open this one
# file, scan the table, then click into the per-listing details below.


def render_case_summary_html(
    case_id: str,
    allegations: list[dict],
    candidates: list,                              # list[DBCandidate]
    leaf_results_by_listing: dict[str, dict[str, LeafResult]],
    listing_outcomes: list[dict],
    chunks_by_id: dict[str, Chunk],
    listings_by_code: dict[str, Listing],
    root_verdicts_by_code: dict[str, NodeVerdict],
    source_pdf_path: Path | None = None,
) -> str:
    """Render a single HTML document with summary table + all listing forms.

    Args:
        case_id: human-readable case ID (e.g. '1234567')
        allegations: list of {text, source_chunk_pk, source_chunk_id, ...}
            from get_allegations_for_case() or run_from_db's allegation_rows.
        candidates: list of DBCandidate objects from find_candidates_sql.
            We use candidate.reasoning bits to map allegations -> listings.
        leaf_results_by_listing: {listing_code: {leaf_path: LeafResult}}
            from the matcher's run.
        listing_outcomes: list of {listing_pk, listing_code, listing_title,
            form_verdict, groundedness_score, candidate_rank}.
        chunks_by_id: {chunk_id_str: Chunk} for citation rendering.
        listings_by_code: {listing_code: Listing} so we can pass each into
            render_form_html for the detail sections.
        root_verdicts_by_code: {listing_code: NodeVerdict} (consolidated root)
        source_pdf_path: optional, enables clickable citations.
    """
    # --- Build allegation -> listing mapping by parsing candidate.reasoning ---
    # Each candidate.reasoning entry looks like:
    #   "Lung cancer ~ summary (0.78)"
    # We match the leading allegation text against each allegation in our
    # list to attribute the candidate.
    alleg_to_candidates: dict[int, list] = {}      # alleg index -> list of candidates
    unmatched_candidates: list = []
    for cand in candidates:
        attributed = False
        for bit in cand.reasoning or []:
            # Split at " ~ summary" to get the allegation prefix
            alleg_prefix = bit.split(" ~ summary")[0].strip()
            for i, alleg in enumerate(allegations):
                if alleg_prefix.lower() in alleg["text"].lower() or \
                        alleg["text"].lower() in alleg_prefix.lower():
                    alleg_to_candidates.setdefault(i, []).append(cand)
                    attributed = True
                    break
            if attributed:
                break
        if not attributed:
            unmatched_candidates.append(cand)

    # --- For each (allegation, candidate) row, pick the strongest evidence ---
    def best_evidence_for_listing(listing_code: str) -> tuple[Chunk | None, str, str]:
        """Pick the single most authoritative cited chunk + its quote.
        Returns (chunk, quote, leaf_path) or (None, '', '')."""
        leaf_results = leaf_results_by_listing.get(listing_code, {})
        # Prefer leaves with verdict='met', then evidence_strength logic,
        # then by chunk's encounter_date / page recency. Simplest heuristic:
        # take the first leaf with verdict=met and at least one evidence item.
        best_chunk = None
        best_quote = ""
        best_leaf_path = ""
        # Pass 1: any met-verdict leaf with evidence
        for path, lr in leaf_results.items():
            if lr.verdict == "met" and lr.evidence:
                ev = lr.evidence[0]
                chunk = chunks_by_id.get(ev.chunk_id)
                if chunk:
                    return chunk, ev.quote, path
        # Pass 2: any not_met-verdict leaf with evidence
        for path, lr in leaf_results.items():
            if lr.verdict == "not_met" and lr.evidence:
                ev = lr.evidence[0]
                chunk = chunks_by_id.get(ev.chunk_id)
                if chunk:
                    return chunk, ev.quote, path
        # Pass 3: any leaf with any evidence (insufficient with cited chunks)
        for path, lr in leaf_results.items():
            if lr.evidence:
                ev = lr.evidence[0]
                chunk = chunks_by_id.get(ev.chunk_id)
                if chunk:
                    return chunk, ev.quote, path
        return None, "", ""

    # --- Build the summary table rows ---
    outcomes_by_code = {o["listing_code"]: o for o in listing_outcomes}

    def render_evidence_cell(chunk: Chunk | None, quote: str) -> str:
        if not chunk:
            return '<em style="color: #888;">No chart evidence found</em>'
        provider = chunk.doc_title or chunk.doc_type or "?"
        # Strip leading e.g. "doc-04 — " prefix from doc_title if present
        if " — " in provider:
            provider = provider.split(" — ", 1)[1].strip()
        date = chunk.encounter_date or "?"
        page = chunk.page_start or 0
        section = chunk.section or "?"
        href = _pdf_page_link(source_pdf_path, page) if page else None
        link_html = (
            f'<a href="{escape(href)}" target="_blank" rel="noopener">'
            f'page {page}</a>'
        ) if href else f'page {page}'
        quote_short = quote[:200] + "..." if len(quote) > 200 else quote
        return (
            f'<div class="ev-meta">'
            f'<strong>Provider:</strong> {escape(provider)}<br>'
            f'<strong>Date of Service:</strong> {escape(date)}<br>'
            f'<strong>Section:</strong> {escape(section)} ({link_html})'
            f'</div>'
            f'<div class="ev-quote">"<em>{escape(quote_short)}</em>"</div>'
        )

    def render_listing_cell(listing_code: str) -> str:
        outcome = outcomes_by_code.get(listing_code, {})
        title = outcome.get("listing_title", "")
        verdict = outcome.get("form_verdict", "")
        grounded = outcome.get("groundedness_score", 0)
        verdict_class = {
            "Meets": "v-met",
            "Does not meet/equal": "v-not_met",
        }.get(verdict, "v-insufficient")
        anchor = f"listing-{listing_code.replace('.', '-')}"
        return (
            f'<a href="#{anchor}" class="listing-link">'
            f'<strong>{escape(listing_code)}</strong> {escape(title)}</a><br>'
            f'<span class="cell-verdict {verdict_class}">{escape(verdict)}</span> '
            f'<span class="cell-grounded">groundedness {grounded:.2f}</span>'
        )

    # Build table rows. ONLY include rows where an allegation cleanly maps to
    # a candidate listing -- per the user's spec, the summary table is the
    # "primary findings" view, not an exhaustive log. Allegations with no
    # candidate (and candidates with no allegation attribution) are dropped
    # from the table; both are still represented in the detail sections and
    # the sidebar navigation, so nothing is hidden.
    table_rows = []
    for i, alleg in enumerate(allegations):
        cands = alleg_to_candidates.get(i, [])
        if not cands:
            continue   # skip allegations without a matched listing
        alleg_text = escape(alleg.get("text", ""))
        for cand in cands:
            code = cand.listing.code
            chunk, quote, _leaf_path = best_evidence_for_listing(code)
            ev_cell = render_evidence_cell(chunk, quote)
            listing_cell = render_listing_cell(code)
            table_rows.append(
                f'<tr><td>{alleg_text}</td><td>{ev_cell}</td><td>{listing_cell}</td></tr>'
            )

    rows_html = "\n".join(table_rows) or \
                '<tr><td colspan="3"><em>No allegations cleanly mapped to a candidate listing. ' \
                'See sidebar for all candidate listings the matcher surfaced.</em></td></tr>'

    # --- Headline summary ---
    n_meets = sum(1 for o in listing_outcomes if o["form_verdict"] == "Meets")
    n_dnm = sum(1 for o in listing_outcomes if o["form_verdict"] == "Does not meet/equal")
    n_insuf = sum(1 for o in listing_outcomes if "Insufficient" in o["form_verdict"])
    avg_grounded = (
        sum(o.get("groundedness_score") or 0 for o in listing_outcomes)
        / max(1, len(listing_outcomes))
    )

    # --- Left sidebar nav: listings grouped by verdict priority ---
    # Order: Meets first (most action-needed), then Does not meet (clear AI calls),
    # then Insufficient (reviewer must investigate). Within each group, sort by
    # groundedness desc (highest confidence first).
    def verdict_group(v: str) -> int:
        if v == "Meets":
            return 0
        if v == "Does not meet/equal":
            return 1
        return 2  # Insufficient or any catch-all

    sidebar_items = sorted(
        listing_outcomes,
        key=lambda o: (
            verdict_group(o["form_verdict"]),
            -float(o.get("groundedness_score") or 0),
            o.get("candidate_rank", 99),
        ),
    )
    nav_groups: list[tuple[str, str, list[dict]]] = [
        ("Meets",                       "v-met",          []),
        ("Does not meet/equal",         "v-not_met",      []),
        ("Insufficient evidence",       "v-insufficient", []),
    ]
    for o in sidebar_items:
        if o["form_verdict"] == "Meets":
            nav_groups[0][2].append(o)
        elif o["form_verdict"] == "Does not meet/equal":
            nav_groups[1][2].append(o)
        else:
            nav_groups[2][2].append(o)

    sidebar_links = []
    for group_label, group_class, items in nav_groups:
        if not items:
            continue
        sidebar_links.append(
            f'<div class="nav-group-header {group_class}">{escape(group_label)}'
            f' <span class="nav-count">({len(items)})</span></div>'
        )
        for o in items:
            code = o["listing_code"]
            title = o.get("listing_title", "")
            grounded = o.get("groundedness_score", 0) or 0
            short_title = (title[:38] + "...") if len(title) > 38 else title
            anchor = f"listing-{code.replace('.', '-')}"
            sidebar_links.append(
                f'<a class="nav-item {group_class}" href="#{anchor}">'
                f'<span class="nav-code">{escape(code)}</span>'
                f'<span class="nav-title">{escape(short_title)}</span>'
                f'<span class="nav-grounded">{grounded:.2f}</span>'
                f'</a>'
            )
    sidebar_html = "\n".join(sidebar_links) or \
                   '<p style="color:#888;font-size:0.85em;padding:0.5em;">No candidates surfaced.</p>'

    # --- Detail sections (one per listing) ---
    detail_sections = []
    # Order: candidate_rank ascending (best-first)
    ordered_codes = sorted(
        outcomes_by_code.keys(),
        key=lambda c: outcomes_by_code[c].get("candidate_rank", 99),
    )
    for code in ordered_codes:
        listing = listings_by_code.get(code)
        root = root_verdicts_by_code.get(code)
        leaf_results = leaf_results_by_listing.get(code, {})
        if not listing or not root:
            continue
        # Reuse render_form_html for the full per-listing form
        form_html = render_form_html(
            listing=listing,
            root_verdict=root,
            leaf_results=leaf_results,
            case_id=case_id,
            chunks_by_id=chunks_by_id,
            source_pdf_path=source_pdf_path,
        )
        # Extract just the <body> contents from the rendered form — we don't
        # want a full <html> nested inside our own. Slice from after <body>
        # to before </body>.
        body_start = form_html.find("<body>")
        body_end = form_html.rfind("</body>")
        inner = form_html[body_start + 6:body_end] if body_start >= 0 else form_html
        anchor = f"listing-{code.replace('.', '-')}"
        detail_sections.append(
            f'<section id="{anchor}" class="listing-detail">'
            f'<div class="back-to-top"><a href="#top">↑ Back to summary table</a></div>'
            f'{inner}</section>'
        )

    return _CASE_SUMMARY_TEMPLATE.format(
        case_id=escape(case_id),
        n_meets=n_meets,
        n_dnm=n_dnm,
        n_insuf=n_insuf,
        n_total=len(listing_outcomes),
        avg_grounded=avg_grounded,
        sidebar_html=sidebar_html,
        table_rows=rows_html,
        detail_sections="\n\n".join(detail_sections),
    )


_CASE_SUMMARY_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Case {case_id} — Disability Review Summary</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         line-height: 1.5; color: #1a1a1a; margin: 0; padding: 0; }}
  /* Main content sits to the right of the fixed sidebar */
  .main {{ max-width: 1000px; margin-left: 290px; margin-right: auto;
           padding: 2em 2em 4em 2em; }}
  /* Fixed left navigation sidebar */
  .sidebar {{ position: fixed; left: 0; top: 0; bottom: 0; width: 270px;
              background: #1a3a5c; color: #fff; overflow-y: auto;
              padding: 1em 0.5em 1.5em 0.5em; box-shadow: 2px 0 8px rgba(0,0,0,0.15);
              font-size: 0.88em; }}
  .sidebar h2 {{ color: #fff; font-size: 1em; margin: 0.5em 0.5em 0.8em 0.5em;
                 padding-bottom: 0.4em; border-bottom: 1px solid #345779; }}
  .nav-group-header {{ font-weight: 700; font-size: 0.78em; text-transform: uppercase;
                       letter-spacing: 0.04em; padding: 0.7em 0.5em 0.3em 0.5em;
                       border-top: 1px solid #345779; margin-top: 0.4em; color: #b8d4ee; }}
  .nav-group-header:first-child {{ border-top: none; margin-top: 0; }}
  .nav-group-header .nav-count {{ font-weight: 400; color: #88a4c4; }}
  .nav-group-header.v-met {{ color: #7adf9e; }}
  .nav-group-header.v-not_met {{ color: #f99494; }}
  .nav-group-header.v-insufficient {{ color: #ffd76e; }}
  .nav-item {{ display: flex; align-items: center; gap: 0.4em; padding: 0.45em 0.5em;
               margin: 0.1em 0; border-radius: 4px; text-decoration: none; color: #e8eef5;
               border-left: 3px solid transparent; transition: background 0.1s; }}
  .nav-item:hover {{ background: #234c75; }}
  .nav-item.v-met {{ border-left-color: #1e8e3e; }}
  .nav-item.v-not_met {{ border-left-color: #d93025; }}
  .nav-item.v-insufficient {{ border-left-color: #f9ab00; }}
  .nav-code {{ font-family: ui-monospace, monospace; font-weight: 700;
               min-width: 3.5em; flex-shrink: 0; color: #fff; }}
  .nav-title {{ flex: 1; color: #cfd9e5; font-size: 0.92em; line-height: 1.25; }}
  .nav-grounded {{ font-size: 0.78em; color: #88a4c4; font-family: ui-monospace, monospace;
                   flex-shrink: 0; }}
  /* Narrow screens: stack sidebar above content rather than fixed-left */
  @media (max-width: 900px) {{
    .sidebar {{ position: static; width: auto; height: auto; }}
    .main {{ margin-left: auto; padding: 1em; }}
  }}
  h1, h2, h3, h4 {{ color: #0a0a0a; }}
  h1 {{ font-size: 1.6em; margin-bottom: 0; }}
  .org {{ color: #555; font-size: 0.95em; margin-top: 0.3em; margin-bottom: 1.5em; }}
  .case-headline {{ background: #f5f5f5; padding: 1em 1.5em; border-radius: 6px;
                    margin: 1em 0 2em 0; font-size: 1.05em; }}
  .case-headline .num {{ font-weight: 700; font-size: 1.4em; color: #1a56c4; }}
  .case-headline .pill {{ display: inline-block; padding: 0.15em 0.6em; margin: 0 0.3em;
                          border-radius: 12px; font-size: 0.85em; font-weight: 600; }}
  .pill.met {{ background: #e6f4ea; color: #0b6027; border: 1px solid #1e8e3e; }}
  .pill.dnm {{ background: #fce8e6; color: #8c1d18; border: 1px solid #d93025; }}
  .pill.insuf {{ background: #fef7e0; color: #7a5300; border: 1px solid #f9ab00; }}
  table.summary {{ width: 100%; border-collapse: collapse; margin: 1em 0 2em 0; }}
  table.summary th {{ background: #1a3a5c; color: #fff; padding: 0.8em 1em;
                       text-align: left; font-size: 0.95em; vertical-align: top; }}
  table.summary td {{ padding: 0.8em 1em; border: 1px solid #d0d4d9;
                       vertical-align: top; font-size: 0.92em; }}
  table.summary tr:nth-child(even) td {{ background: #f8f9fa; }}
  .ev-meta {{ font-size: 0.88em; line-height: 1.45; margin-bottom: 0.4em; }}
  .ev-quote {{ background: #fafafa; padding: 0.4em 0.6em;
                border-left: 3px solid #aac4f5; font-size: 0.88em; }}
  .listing-link {{ color: #1a56c4; text-decoration: none; }}
  .listing-link:hover {{ text-decoration: underline; }}
  .cell-verdict {{ display: inline-block; padding: 0.1em 0.55em; margin-top: 0.3em;
                    border-radius: 10px; font-size: 0.82em; font-weight: 600; }}
  .cell-verdict.v-met {{ background: #e6f4ea; color: #0b6027; }}
  .cell-verdict.v-not_met {{ background: #fce8e6; color: #8c1d18; }}
  .cell-verdict.v-insufficient {{ background: #fef7e0; color: #7a5300; }}
  .cell-grounded {{ color: #555; font-size: 0.82em; }}
  .listing-detail {{ border-top: 3px solid #1a3a5c; padding-top: 1em; margin-top: 3em; }}
  .back-to-top {{ font-size: 0.85em; margin-bottom: 0.5em; }}
  .back-to-top a {{ color: #1a56c4; text-decoration: none; }}
  /* Inherit per-listing form styles from render_form_html — these mirror what's there */
  .meta {{ background: #f5f5f5; padding: 0.5em 1em; border-left: 4px solid #888;
          margin: 1em 0; font-size: 0.95em; }}
  .verdict {{ font-size: 1.3em; padding: 0.6em 1em; margin: 1.5em 0;
             border: 2px solid; border-radius: 6px; }}
  .verdict.v-met        {{ background: #e6f4ea; border-color: #1e8e3e; color: #0b6027; }}
  .verdict.v-not_met    {{ background: #fce8e6; border-color: #d93025; color: #8c1d18; }}
  .verdict.v-insufficient {{ background: #fef7e0; border-color: #f9ab00; color: #7a5300; }}
  .box {{ font-size: 1.1em; padding: 0 0.2em; }}
  .box.met {{ color: #1e8e3e; }}
  .box.not_met {{ color: #888; }}
  .box.insufficient {{ color: #f9ab00; }}
  .leaf, .internal {{ margin: 0.6em 0; padding: 0.4em 0.6em; border-left: 3px solid #ccc; }}
  .leaf.v-met        {{ border-left-color: #1e8e3e; background: #f4fbf6; }}
  .leaf.v-not_met    {{ border-left-color: #d93025; background: #fdf3f2; }}
  .leaf.v-insufficient {{ border-left-color: #f9ab00; background: #fef9eb; }}
  .leaf-path {{ font-weight: 600; font-family: ui-monospace, monospace; }}
  .leaf-crit {{ color: #333; }}
  .rationale {{ margin-top: 0.3em; color: #444; }}
  .evidence {{ list-style: none; padding-left: 0; margin: 0.4em 0; }}
  .evidence li {{ margin: 0.35em 0; padding: 0.25em 0.5em;
                  background: #fff; border-left: 2px solid #ccd; }}
  a.cite {{ display: inline-block; padding: 0 0.35em; background: #e8f0fe;
            border: 1px solid #aac4f5; border-radius: 4px; color: #1a56c4;
            text-decoration: none; font-size: 0.85em; font-weight: 600; }}
  a.cite:hover {{ background: #d0dffb; }}
  .cite-label {{ color: #555; font-style: italic; font-size: 0.9em; }}
  .quote {{ color: #1a1a1a; }}
  blockquote.quote {{ margin: 0.3em 0 0.6em 1.5em; padding: 0.3em 0.6em;
                      border-left: 3px solid #aac4f5; color: #222; font-style: italic; }}
  .citations code {{ font-size: 0.85em; background: #f0f0f0;
                     padding: 1px 4px; border-radius: 3px; }}
  hr.section {{ border: none; border-top: 1px solid #ddd; margin: 2em 0; }}
  .disclaimer {{ font-size: 0.85em; color: #666; margin-top: 2em;
                  border-top: 1px solid #ddd; padding-top: 1em; }}
</style>
</head>
<body id="top">

<nav class="sidebar" aria-label="Listing navigation">
  <h2>Listings</h2>
  {sidebar_html}
</nav>

<div class="main">

<h1>Case {case_id} — Disability Review Summary</h1>
<p class="org">UMass Chan Medical School — Disability Evaluation Services — SSI Listings (Adult)</p>

<div class="case-headline">
  <span class="num">{n_total}</span> candidate listing(s) evaluated:
  <span class="pill met">{n_meets} Meets</span>
  <span class="pill dnm">{n_dnm} Does not meet</span>
  <span class="pill insuf">{n_insuf} Insufficient</span>
  &nbsp; | &nbsp; Overall groundedness: <strong>{avg_grounded:.2f}</strong>
</div>

<h2>Possible Visualization of Output Report</h2>
<table class="summary">
  <thead>
    <tr>
      <th style="width: 22%;">1. List of Impairments Alleged in Supplement</th>
      <th style="width: 43%;">2. Medical Evidence Found</th>
      <th style="width: 35%;">3. SSI Listing Met<br>(blue book or "Cheat Sheet")</th>
    </tr>
  </thead>
  <tbody>
{table_rows}
  </tbody>
</table>

<hr class="section">
<h2>Detailed Listing Evaluations</h2>
<p style="color:#555; font-size:0.9em;">Click any listing in the table above to jump to its
detailed form below. Each form shows the AND/OR criterion tree, per-leaf verdicts, and
chart citations.</p>

{detail_sections}

<p class="disclaimer">
  Auto-generated by the MassHealth Disability Reviewer Assistant. Reviewer must verify
  all citations against the source PDF before signing.
</p>

</div><!-- /.main -->
</body>
</html>
"""


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 960px; margin: 2em auto; padding: 0 1em; line-height: 1.5; color: #1a1a1a; }}
  h1, h2, h3, h4 {{ color: #0a0a0a; }}
  h1 {{ font-size: 1.2em; margin-bottom: 0; }}
  .org {{ color: #555; font-size: 0.9em; margin-top: 0.3em; }}
  .open-packet a {{ font-size: 0.95em; color: #0066cc; }}
  .meta {{ background: #f5f5f5; padding: 0.5em 1em; border-left: 4px solid #888;
          margin: 1em 0; font-size: 0.95em; }}
  .verdict {{ font-size: 1.3em; padding: 0.6em 1em; margin: 1.5em 0;
             border: 2px solid; border-radius: 6px; }}
  .verdict.v-met        {{ background: #e6f4ea; border-color: #1e8e3e; color: #0b6027; }}
  .verdict.v-not_met    {{ background: #fce8e6; border-color: #d93025; color: #8c1d18; }}
  .verdict.v-insufficient {{ background: #fef7e0; border-color: #f9ab00; color: #7a5300; }}
  .box {{ font-size: 1.1em; padding: 0 0.2em; }}
  .box.met {{ color: #1e8e3e; }}
  .box.not_met {{ color: #888; }}
  .box.insufficient {{ color: #f9ab00; }}
  .leaf, .internal {{ margin: 0.6em 0; padding: 0.4em 0.6em;
                       border-left: 3px solid #ccc; }}
  .leaf.v-met        {{ border-left-color: #1e8e3e; background: #f4fbf6; }}
  .leaf.v-not_met    {{ border-left-color: #d93025; background: #fdf3f2; }}
  .leaf.v-insufficient {{ border-left-color: #f9ab00; background: #fef9eb; }}
  .leaf-path {{ font-weight: 600; font-family: ui-monospace, monospace; }}
  .leaf-crit {{ color: #333; }}
  .rationale {{ margin-top: 0.3em; color: #444; }}
  .evidence {{ list-style: none; padding-left: 0; margin: 0.4em 0; }}
  .evidence li {{ margin: 0.35em 0; padding: 0.25em 0.5em;
                  background: #fff; border-left: 2px solid #ccd; }}
  a.cite {{ display: inline-block; padding: 0 0.35em; background: #e8f0fe;
            border: 1px solid #aac4f5; border-radius: 4px;
            color: #1a56c4; text-decoration: none; font-size: 0.85em;
            font-weight: 600; }}
  a.cite:hover {{ background: #d0dffb; }}
  .cite-label {{ color: #555; font-style: italic; font-size: 0.9em; }}
  .quote {{ color: #1a1a1a; }}
  blockquote.quote {{ margin: 0.3em 0 0.6em 1.5em; padding: 0.3em 0.6em;
                      border-left: 3px solid #aac4f5; color: #222; font-style: italic; }}
  .citations code {{ font-size: 0.85em; background: #f0f0f0;
                     padding: 1px 4px; border-radius: 3px; }}
  hr.section {{ border: none; border-top: 1px solid #ddd; margin: 2em 0; }}
  .disclaimer {{ font-size: 0.85em; color: #666; margin-top: 2em;
                  border-top: 1px solid #ddd; padding-top: 1em; }}
</style>
</head>
<body>

<h1>University of Massachusetts Chan Medical School</h1>
<p class="org">Disability Evaluation Services — SSI Listings — Adult</p>

<div class="meta">
  <strong>Case #:</strong> {case_id} &nbsp;|&nbsp;
  <strong>Listing:</strong> {listing_code} — {listing_title} &nbsp;|&nbsp;
  <strong>Body system:</strong> {body_system}
</div>

{open_packet}

<div class="verdict {verdict_class}">
  <strong>Verdict:</strong> {verdict_label}
</div>

<hr class="section">
<h2>Criteria</h2>
{criteria_html}

<hr class="section">
<h2>Objective Medical Evidence and Other Additional Information</h2>
{narrative_html}

<hr class="section">
{citations_html}

<p class="disclaimer">
  Auto-generated. Reviewer must verify all citations against the source PDF before signing.
  Click any <a class="cite" href="#">[N]</a> badge to open the packet at the cited page.
</p>

</body>
</html>
"""
