"""Render a populated Matched_Listing form per evaluated listing.

Two outputs:
  render_form()       -> markdown (for diff-ability and CLI viewing)
  render_form_html()  -> HTML with clickable citations that open the source
                          PDF at the cited page. Open in any modern browser
                          (Edge, Chrome, Firefox) — clicking a citation uses
                          the standard PDF #page=N URL fragment.

Both layouts mirror the UMass Chan DES form:
  - Header (DIAGNOSIS, CASE #, listing code + title)
  - Each criterion with met/not/insufficient checkbox
  - Tri-state verdict (Meets / Equals / Does not meet/equal)
  - Objective Medical Evidence narrative composed from per-leaf citations
  - Citations index at the end
"""
from html import escape
from pathlib import Path
from urllib.parse import quote

from .chunks import Chunk, Listing
from .consolidate import NodeVerdict, form_verdict
from .evaluate import LeafResult


def render_form(
    listing: Listing,
    root_verdict: NodeVerdict,
    leaf_results: dict[str, LeafResult],
    case_id: str,
    chunks_by_id: dict[str, Chunk],
) -> str:
    lines = []
    lines.append("UNIVERSITY OF MASSACHUSETTS CHAN MEDICAL SCHOOL")
    lines.append("DISABILITY EVALUATION SERVICES — SSI LISTINGS — ADULT")
    lines.append("")
    lines.append(f"**DIAGNOSIS:** {listing.title}")
    lines.append(f"**CASE #:** {case_id}")
    lines.append("")
    lines.append(f"## {listing.code} — {listing.title}")
    lines.append(f"*Body system: {listing.body_system}*")
    lines.append("")
    lines.append("### Criteria")
    lines.append("")

    # Render every leaf with its verdict.
    citation_pool: list[tuple[str, Chunk, str]] = []  # (citation_marker, chunk, quote)
    citation_seen: dict[str, str] = {}  # chunk_id -> marker

    def cite(chunk_id: str, chunk: Chunk, quote: str) -> str:
        if chunk_id in citation_seen:
            return citation_seen[chunk_id]
        marker = f"[{len(citation_pool) + 1}]"
        citation_seen[chunk_id] = marker
        citation_pool.append((marker, chunk, quote))
        return marker

    def render_node(node: NodeVerdict, depth: int = 0):
        indent = "  " * depth
        if node.logic is None:
            # leaf
            box = _checkbox(node.verdict)
            lines.append(f"{indent}- {box} **{node.path}** — {node.criterion or ''}")
            lr = leaf_results.get(node.path)
            if lr and lr.rationale:
                lines.append(f"{indent}  *Rationale:* {lr.rationale}")
            if lr and lr.evidence:
                for ev in lr.evidence:
                    chunk = chunks_by_id.get(ev.chunk_id)
                    if not chunk:
                        continue
                    marker = cite(ev.chunk_id, chunk, ev.quote)
                    lines.append(
                        f"{indent}  - {marker} *{_chunk_label(chunk)}:* "
                        f"\"{ev.quote}\""
                    )
        else:
            # internal
            label = f"{node.path} ({node.logic})"
            if node.criterion:
                label += f" — {node.criterion}"
            box = _checkbox(node.verdict)
            lines.append(f"{indent}- {box} **{label}**")
            for child in node.children:
                render_node(child, depth + 1)

    render_node(root_verdict)
    lines.append("")

    # Top-level verdict.
    lines.append("### CHECK CRITERIA MET")
    lines.append("")
    verdict_label = form_verdict(root_verdict)
    lines.append(f"**Verdict:** **{verdict_label}**")
    lines.append("")
    lines.append(f"- {'☒' if verdict_label == 'Meets' else '☐'} Meets")
    lines.append("- ☐ Equals  *(equivalence reasoning not implemented in stub)*")
    lines.append(
        f"- {'☒' if verdict_label.startswith('Does not') else '☐'} Does not meet/equal"
    )
    if verdict_label.startswith("Insufficient"):
        lines.append(f"- ☒ Insufficient evidence — reviewer must verify against chart")
    lines.append("")
    lines.append("Disability Reviewer #: __________   Physician Advisor #: __________")
    lines.append("")

    # Objective medical evidence narrative.
    lines.append("### OBJECTIVE MEDICAL EVIDENCE AND OTHER ADDITIONAL INFORMATION")
    lines.append("")
    narrative = _compose_narrative(root_verdict, leaf_results, chunks_by_id, citation_seen, citation_pool, cite)
    lines.append(narrative)
    lines.append("")

    # Citations index.
    if citation_pool:
        lines.append("### Citations")
        lines.append("")
        for marker, chunk, _quote in citation_pool:
            lines.append(
                f"- {marker} `{chunk.chunk_id}` — "
                f"{_chunk_label(chunk)}"
            )
        lines.append("")

    lines.append("---")
    lines.append("*Auto-generated by stub pipeline. Reviewer must verify all citations against source PDF before signing.*")

    return "\n".join(lines)


def _checkbox(verdict: str) -> str:
    return {
        "met": "☒",
        "not_met": "☐",
        "insufficient": "?",
    }.get(verdict, "?")


def _chunk_label(chunk: Chunk) -> str:
    """Render a chunk's metadata as a human-readable citation tag."""
    bits = []
    if chunk.doc_title:
        bits.append(chunk.doc_title.split("—")[-1].strip() if "—" in chunk.doc_title else chunk.doc_title)
    elif chunk.doc_type:
        bits.append(chunk.doc_type.replace("_", " "))
    if chunk.section:
        bits.append(chunk.section)
    if chunk.encounter_date:
        bits.append(chunk.encounter_date)
    bits.append(f"p.{chunk.page_start}")
    return ", ".join(bits)


def _compose_narrative(
    root: NodeVerdict,
    leaf_results: dict,
    chunks_by_id: dict,
    citation_seen: dict,
    citation_pool: list,
    cite,
) -> str:
    """Compose a reviewer-facing prose summary from per-leaf evidence."""
    paragraphs = []

    def walk(node: NodeVerdict):
        if node.logic is None:
            lr = leaf_results.get(node.path)
            if not lr:
                return
            if node.verdict == "met" and lr.evidence:
                lines = [f"**{node.path} ({node.verdict}):** {lr.rationale}"]
                for ev in lr.evidence:
                    chunk = chunks_by_id.get(ev.chunk_id)
                    if not chunk:
                        continue
                    marker = cite(ev.chunk_id, chunk, ev.quote)
                    lines.append(
                        f"  > {marker} *{_chunk_label(chunk)}*:  \n"
                        f"  > \"{ev.quote}\""
                    )
                paragraphs.append("\n".join(lines))
            elif node.verdict == "not_met":
                paragraphs.append(
                    f"**{node.path}:** Not met. {lr.rationale}"
                )
            elif node.verdict == "insufficient":
                paragraphs.append(
                    f"**{node.path}:** Insufficient evidence in record. {lr.rationale}"
                )
        else:
            for c in node.children:
                walk(c)

    walk(root)
    if not paragraphs:
        return "*No per-criterion evidence available.*"
    return "\n\n".join(paragraphs)


def write_form(out_path: Path, content: str):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")


# =============================================================================
# HTML renderer with clickable page-level citations
# =============================================================================

def _pdf_page_link(source_pdf_path: Path | None, page: int) -> str | None:
    """Return a file:// URL with #page=N fragment that all major PDF viewers
    honor (Adobe Reader, Edge/Chrome built-in viewer, Firefox PDF.js).
    Returns None if no source PDF path was provided."""
    if not source_pdf_path:
        return None
    # Path.as_uri() handles the file:// scheme + URL-encoding of spaces/specials.
    return f"{source_pdf_path.resolve().as_uri()}#page={page}"


def render_form_html(
    listing: Listing,
    root_verdict: NodeVerdict,
    leaf_results: dict[str, LeafResult],
    case_id: str,
    chunks_by_id: dict[str, Chunk],
    source_pdf_path: Path | None = None,
) -> str:
    """Render an HTML form. Citation markers become clickable links that open
    the source PDF at the cited page. If source_pdf_path is None, citations
    render as plain text (with page numbers but no link).
    """
    verdict_label = form_verdict(root_verdict)

    # Track citations as we encounter them so we can render an index + reuse markers.
    citation_pool: list[tuple[str, Chunk, str]] = []
    citation_seen: dict[str, str] = {}

    def cite(chunk: Chunk, quote: str) -> str:
        if chunk.chunk_id in citation_seen:
            return citation_seen[chunk.chunk_id]
        marker = f"[{len(citation_pool) + 1}]"
        citation_seen[chunk.chunk_id] = marker
        citation_pool.append((marker, chunk, quote))
        return marker

    def cite_link(chunk: Chunk, quote: str) -> str:
        marker = cite(chunk, quote)
        href = _pdf_page_link(source_pdf_path, chunk.page_start)
        if href:
            return (
                f'<a class="cite" href="{escape(href)}" '
                f'title="Open packet PDF at p.{chunk.page_start}" '
                f'target="_blank" rel="noopener">{marker}</a>'
            )
        return f'<span class="cite">{marker}</span>'

    def render_node_html(node: NodeVerdict, depth: int = 0) -> str:
        indent_px = depth * 18
        if node.logic is None:
            box = _checkbox_html(node.verdict)
            lr = leaf_results.get(node.path)
            crit = escape(node.criterion or "")
            html = (
                f'<div class="leaf v-{node.verdict}" style="margin-left:{indent_px}px">'
                f'<div class="leaf-header">{box} <span class="leaf-path">{escape(node.path)}</span> '
                f'<span class="leaf-crit">— {crit}</span></div>'
            )
            if lr and lr.rationale:
                html += f'<div class="rationale"><em>Rationale:</em> {escape(lr.rationale)}</div>'
            if lr and lr.evidence:
                html += '<ul class="evidence">'
                for ev in lr.evidence:
                    chunk = chunks_by_id.get(ev.chunk_id)
                    if not chunk:
                        continue
                    marker_html = cite_link(chunk, ev.quote)
                    label = escape(_chunk_label(chunk))
                    quote_html = escape(ev.quote)
                    html += (
                        f'<li>{marker_html} '
                        f'<span class="cite-label">{label}:</span> '
                        f'<span class="quote">"{quote_html}"</span></li>'
                    )
                html += '</ul>'
            html += '</div>'
            return html
        else:
            box = _checkbox_html(node.verdict)
            label = f"{escape(node.path)} ({escape(node.logic)})"
            if node.criterion:
                label += f" — {escape(node.criterion)}"
            inner = "\n".join(render_node_html(c, depth + 1) for c in node.children)
            return (
                f'<div class="internal v-{node.verdict}" style="margin-left:{indent_px}px">'
                f'<div class="internal-header">{box} <strong>{label}</strong></div>'
                f'{inner}</div>'
            )

    body_criteria = render_node_html(root_verdict)

    # Build the narrative
    narrative_parts: list[str] = []

    def walk_narrative(node: NodeVerdict):
        if node.logic is None:
            lr = leaf_results.get(node.path)
            if not lr:
                return
            head = f'<h4 class="v-{node.verdict}">{escape(node.path)} ({node.verdict})</h4>'
            body = f'<p>{escape(lr.rationale)}</p>'
            quotes_html = ""
            if node.verdict == "met" and lr.evidence:
                quotes_html = '<ul class="evidence">'
                for ev in lr.evidence:
                    chunk = chunks_by_id.get(ev.chunk_id)
                    if not chunk:
                        continue
                    marker_html = cite_link(chunk, ev.quote)
                    label = escape(_chunk_label(chunk))
                    quote_html = escape(ev.quote)
                    quotes_html += (
                        f'<li>{marker_html} <span class="cite-label">{label}:</span> '
                        f'<blockquote class="quote">"{quote_html}"</blockquote></li>'
                    )
                quotes_html += '</ul>'
            narrative_parts.append(head + body + quotes_html)
        else:
            for c in node.children:
                walk_narrative(c)

    walk_narrative(root_verdict)
    narrative_html = "\n".join(narrative_parts) or "<p><em>No per-criterion evidence available.</em></p>"

    # Citations index
    citations_html = ""
    if citation_pool:
        rows = []
        for marker, chunk, _quote in citation_pool:
            href = _pdf_page_link(source_pdf_path, chunk.page_start)
            link = (
                f'<a href="{escape(href)}" target="_blank" rel="noopener">{marker}</a>'
                if href else marker
            )
            rows.append(
                f'<li>{link} <code>{escape(chunk.chunk_id)}</code> — '
                f'{escape(_chunk_label(chunk))}</li>'
            )
        citations_html = "<h3>Citations</h3><ol class=\"citations\">" + "".join(rows) + "</ol>"

    # Top-of-page link to the whole packet
    open_packet = ""
    if source_pdf_path:
        pkt_uri = source_pdf_path.resolve().as_uri()
        open_packet = (
            f'<p class="open-packet">'
            f'<a href="{escape(pkt_uri)}" target="_blank" rel="noopener">'
            f'Open source PDF: {escape(source_pdf_path.name)}</a></p>'
        )

    return _HTML_TEMPLATE.format(
        title=escape(f"{listing.code} — {listing.title}"),
        case_id=escape(case_id),
        listing_code=escape(listing.code),
        listing_title=escape(listing.title),
        body_system=escape(listing.body_system),
        verdict_label=escape(verdict_label),
        verdict_class={
            "Meets": "v-met",
            "Does not meet/equal": "v-not_met",
        }.get(verdict_label, "v-insufficient"),
        open_packet=open_packet,
        criteria_html=body_criteria,
        narrative_html=narrative_html,
        citations_html=citations_html,
    )


def _checkbox_html(verdict: str) -> str:
    return {
        "met": '<span class="box met">☒</span>',
        "not_met": '<span class="box not_met">☐</span>',
        "insufficient": '<span class="box insufficient">?</span>',
    }.get(verdict, '<span class="box">?</span>')


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 960px; margin: 2em auto; padding: 0 1em; line-height: 1.5; color: #1a1a1a; }}
  h1, h2, h3, h4 {{ color: #0a0a0a; }}
  h1 {{ font-size: 1.2em; margin-bottom: 0; }}
  .org {{ color: #555; font-size: 0.9em; margin-top: 0.3em; }}
  .open-packet a {{ font-size: 0.95em; color: #0066cc; }}
  .meta {{ background: #f5f5f5; padding: 0.5em 1em; border-left: 4px solid #888;
          margin: 1em 0; font-size: 0.95em; }}
  .verdict {{ font-size: 1.3em; padding: 0.6em 1em; margin: 1.5em 0;
             border: 2px solid; border-radius: 6px; }}
  .verdict.v-met        {{ background: #e6f4ea; border-color: #1e8e3e; color: #0b6027; }}
  .verdict.v-not_met    {{ background: #fce8e6; border-color: #d93025; color: #8c1d18; }}
  .verdict.v-insufficient {{ background: #fef7e0; border-color: #f9ab00; color: #7a5300; }}
  .box {{ font-size: 1.1em; padding: 0 0.2em; }}
  .box.met {{ color: #1e8e3e; }}
  .box.not_met {{ color: #888; }}
  .box.insufficient {{ color: #f9ab00; }}
  .leaf, .internal {{ margin: 0.6em 0; padding: 0.4em 0.6em;
                       border-left: 3px solid #ccc; }}
  .leaf.v-met        {{ border-left-color: #1e8e3e; background: #f4fbf6; }}
  .leaf.v-not_met    {{ border-left-color: #d93025; background: #fdf3f2; }}
  .leaf.v-insufficient {{ border-left-color: #f9ab00; background: #fef9eb; }}
  .leaf-path {{ font-weight: 600; font-family: ui-monospace, monospace; }}
  .leaf-crit {{ color: #333; }}
  .rationale {{ margin-top: 0.3em; color: #444; }}
  .evidence {{ list-style: none; padding-left: 0; margin: 0.4em 0; }}
  .evidence li {{ margin: 0.35em 0; padding: 0.25em 0.5em;
                  background: #fff; border-left: 2px solid #ccd; }}
  a.cite {{ display: inline-block; padding: 0 0.35em; background: #e8f0fe;
            border: 1px solid #aac4f5; border-radius: 4px;
            color: #1a56c4; text-decoration: none; font-size: 0.85em;
            font-weight: 600; }}
  a.cite:hover {{ background: #d0dffb; }}
  .cite-label {{ color: #555; font-style: italic; font-size: 0.9em; }}
  .quote {{ color: #1a1a1a; }}
  blockquote.quote {{ margin: 0.3em 0 0.6em 1.5em; padding: 0.3em 0.6em;
                      border-left: 3px solid #aac4f5; color: #222; font-style: italic; }}
  .citations code {{ font-size: 0.85em; background: #f0f0f0;
                     padding: 1px 4px; border-radius: 3px; }}
  hr.section {{ border: none; border-top: 1px solid #ddd; margin: 2em 0; }}
  .disclaimer {{ font-size: 0.85em; color: #666; margin-top: 2em;
                  border-top: 1px solid #ddd; padding-top: 1em; }}
</style>
</head>
<body>

<h1>University of Massachusetts Chan Medical School</h1>
<p class="org">Disability Evaluation Services — SSI Listings — Adult</p>

<div class="meta">
  <strong>Case #:</strong> {case_id} &nbsp;|&nbsp;
  <strong>Listing:</strong> {listing_code} — {listing_title} &nbsp;|&nbsp;
  <strong>Body system:</strong> {body_system}
</div>

{open_packet}

<div class="verdict {verdict_class}">
  <strong>Verdict:</strong> {verdict_label}
</div>

<hr class="section">
<h2>Criteria</h2>
{criteria_html}

<hr class="section">
<h2>Objective Medical Evidence and Other Additional Information</h2>
{narrative_html}

<hr class="section">
{citations_html}

<p class="disclaimer">
  Auto-generated. Reviewer must verify all citations against the source PDF before signing.
  Click any <a class="cite" href="#">[N]</a> badge to open the packet at the cited page.
</p>

</body>
</html>
"""
